const fakeData = [
  {
    id: 1,
    title: "Complete Linux Training",
    instructor: "Jason Cannon",
    price: 49.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/linux/linux-original.svg",
    category: "backend",
    description: "Master Linux system administration and command-line tools for production environments.",
    duration: "10 weeks",
    level: "intermediate",
    rating: 4.7,
    studentsEnrolled: 8500,
  },
  {
    id: 2,
    title: "Modern JavaScript from Scratch",
    instructor: "Jonas Schmedtmann",
    price: 39.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg",
    category: "web-development",
    description: "Learn modern ES6+ JavaScript fundamentals and async programming patterns.",
    duration: "6 weeks",
    level: "beginner",
    rating: 4.8,
    studentsEnrolled: 12000,
  },
  {
    id: 3,
    title: "HTML & CSS Bootcamp",
    instructor: "Colt Steele",
    price: 29.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg",
    category: "web-development",
    description: "Build responsive, accessible websites with semantic HTML5 and modern CSS techniques.",
    duration: "4 weeks",
    level: "beginner",
    rating: 4.6,
    studentsEnrolled: 15000,
  },
  {
    id: 4,
    title: "React.js Complete Guide",
    instructor: "Maximilian Schwarzmuller",
    price: 44.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg",
    category: "web-development",
    description: "Comprehensive React course covering hooks, context, and modern component patterns.",
    duration: "8 weeks",
    level: "intermediate",
    rating: 4.8,
    studentsEnrolled: 18000,
  },
  {
    id: 5,
    title: "Node.js Backend Development",
    instructor: "Andrew Mead",
    price: 42.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original.svg",
    category: "backend",
    description: "Build scalable REST APIs and real-time applications with Node.js and Express.",
    duration: "7 weeks",
    level: "intermediate",
    rating: 4.7,
    studentsEnrolled: 10000,
  },
  {
    id: 6,
    title: "Python for Everybody",
    instructor: "Dr. Charles Severance",
    price: 34.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg",
    category: "data-science",
    description: "Python fundamentals with data analysis, visualization, and machine learning intro.",
    duration: "8 weeks",
    level: "beginner",
    rating: 4.8,
    studentsEnrolled: 20000,
  },
  {
    id: 7,
    title: "Data Structures & Algorithms",
    instructor: "Abdul Bari",
    price: 54.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/java/java-original.svg",
    category: "backend",
    description: "Master essential data structures and algorithmic problem-solving techniques.",
    duration: "12 weeks",
    level: "intermediate",
    rating: 4.9,
    studentsEnrolled: 9000,
  },
  {
    id: 8,
    title: "SQL & Database Design",
    instructor: "Tim Buchalka",
    price: 31.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mysql/mysql-original.svg",
    category: "database",
    description: "Learn relational databases, SQL queries, normalization, and database optimization.",
    duration: "6 weeks",
    level: "beginner",
    rating: 4.6,
    studentsEnrolled: 11000,
  },
  {
    id: 9,
    title: "Full Stack Web Development",
    instructor: "Angela Yu",
    price: 59.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg",
    category: "web-development",
    description: "Complete full-stack bootcamp: frontend, backend, database, and deployment.",
    duration: "16 weeks",
    level: "intermediate",
    rating: 4.8,
    studentsEnrolled: 14000,
  },
  {
    id: 10,
    title: "Git & GitHub Masterclass",
    instructor: "Brad Traversy",
    price: 24.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-original.svg",
    category: "web-development",
    description: "Master version control with Git, GitHub workflows, and collaboration best practices.",
    duration: "3 weeks",
    level: "beginner",
    rating: 4.7,
    studentsEnrolled: 16000,
  },
  {
    id: 11,
    title: "DevOps Fundamentals",
    instructor: "Kunal Kushwaha",
    price: 47.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/docker/docker-original.svg",
    category: "cloud-computing",
    description: "Docker, containerization, CI/CD pipelines, and infrastructure automation basics.",
    duration: "9 weeks",
    level: "intermediate",
    rating: 4.7,
    studentsEnrolled: 7500,
  },
  {
    id: 12,
    title: "Cloud Computing with AWS",
    instructor: "Stephane Maarek",
    price: 64.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/amazonwebservices/amazonwebservices-original-wordmark.svg",
    category: "cloud-computing",
    description: "AWS services, EC2, S3, RDS, Lambda - build and deploy cloud applications.",
    duration: "10 weeks",
    level: "intermediate",
    rating: 4.8,
    studentsEnrolled: 12000,
  },
  /* Trending tech (AI, cloud, security, modern stacks) */
  {
    id: 13,
    title: "Generative AI, LLMs & RAG Systems",
    instructor: "Dr. Harrison Wells",
    price: 69.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/pytorch/pytorch-original.svg",
    category: "data-science",
    description: "Build production-ready LLMs, RAG systems, and explore cutting-edge generative AI.",
    duration: "10 weeks",
    level: "advanced",
    rating: 4.9,
    studentsEnrolled: 5500,
  },
  {
    id: 14,
    title: "TensorFlow & Neural Network Design",
    instructor: "Dr. Priya Natarajan",
    price: 64.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tensorflow/tensorflow-original.svg",
    category: "data-science",
    description: "Deep learning with TensorFlow: CNNs, RNNs, GANs, and advanced architectures.",
    duration: "11 weeks",
    level: "advanced",
    rating: 4.8,
    studentsEnrolled: 6800,
  },
  {
    id: 15,
    title: "MLOps: Deploy & Monitor Models in Production",
    instructor: "Marcus Chen",
    price: 62.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/kubernetes/kubernetes-plain.svg",
    category: "cloud-computing",
    description: "Model serving, monitoring, versioning, and production ML infrastructure.",
    duration: "8 weeks",
    level: "advanced",
    rating: 4.7,
    studentsEnrolled: 4200,
  },
  {
    id: 16,
    title: "Cybersecurity, Zero Trust & Cloud Hardening",
    instructor: "Elena Volkov",
    price: 58.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/bash/bash-original.svg",
    category: "backend",
    description: "Security principles, threat models, zero-trust architecture, and cloud hardening.",
    duration: "9 weeks",
    level: "advanced",
    rating: 4.6,
    studentsEnrolled: 5200,
  },
  {
    id: 17,
    title: "Blockchain, Solidity & Smart Contracts",
    instructor: "Jordan Okonkwo",
    price: 55.99,
    img: "https://cdn.jsdelivr.net/npm/simple-icons@11.14.0/icons/solidity.svg",
    category: "blockchain",
    description: "Ethereum, Solidity smart contracts, security audits, and blockchain architecture.",
    duration: "8 weeks",
    level: "advanced",
    rating: 4.7,
    studentsEnrolled: 4800,
  },
  {
    id: 18,
    title: "Rust Systems Programming & Performance",
    instructor: "Helena Muller",
    price: 52.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/rust/rust-original.svg",
    category: "backend",
    description: "Memory safety, ownership, systems-level programming with Rust and performance optimization.",
    duration: "12 weeks",
    level: "advanced",
    rating: 4.8,
    studentsEnrolled: 5900,
  },
  {
    id: 19,
    title: "Go: Microservices, gRPC & Concurrency",
    instructor: "Sanjay Patel",
    price: 49.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/go/go-original.svg",
    category: "backend",
    description: "Go fundamentals, microservices architecture, gRPC, and concurrent programming.",
    duration: "9 weeks",
    level: "intermediate",
    rating: 4.7,
    studentsEnrolled: 6500,
  },
  {
    id: 20,
    title: "Terraform & Infrastructure as Code",
    instructor: "Rachel Kim",
    price: 48.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/terraform/terraform-original.svg",
    category: "cloud-computing",
    description: "Infrastructure as Code with Terraform, state management, and cloud automation.",
    duration: "7 weeks",
    level: "intermediate",
    rating: 4.6,
    studentsEnrolled: 5100,
  },
  {
    id: 21,
    title: "Kubernetes, Helm & GitOps Workflows",
    instructor: "Tomas Alvarez",
    price: 61.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/kubernetes/kubernetes-plain.svg",
    category: "cloud-computing",
    description: "Container orchestration with Kubernetes, Helm charts, and GitOps deployment patterns.",
    duration: "10 weeks",
    level: "intermediate",
    rating: 4.7,
    studentsEnrolled: 7200,
  },
  {
    id: 22,
    title: "Data Engineering with Apache Spark & Kafka",
    instructor: "Amira Hassan",
    price: 57.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/apachekafka/apachekafka-original.svg",
    category: "database",
    description: "Big data processing, streaming pipelines, Spark, Kafka, and data lake architecture.",
    duration: "10 weeks",
    level: "advanced",
    rating: 4.8,
    studentsEnrolled: 5600,
  },
  {
    id: 23,
    title: "Full Stack with Next.js & Server Components",
    instructor: "Alex Rivera",
    price: 54.99,
    img: "https://cdn.jsdelivr.net/npm/simple-icons@11.14.0/icons/nextdotjs.svg",
    category: "web-development",
    description: "Modern full-stack with Next.js 14+, server components, API routes, and deployment.",
    duration: "9 weeks",
    level: "intermediate",
    rating: 4.8,
    studentsEnrolled: 8900,
  },
  {
    id: 24,
    title: "Kotlin & Modern Android Development",
    instructor: "Li Wei",
    price: 46.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/kotlin/kotlin-original.svg",
    category: "mobile",
    description: "Android development with Kotlin, Jetpack, coroutines, and modern architecture patterns.",
    duration: "10 weeks",
    level: "intermediate",
    rating: 4.7,
    studentsEnrolled: 6200,
  },
  {
    id: 25,
    title: "iOS & SwiftUI App Architecture",
    instructor: "Grace O'Connor",
    price: 48.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/swift/swift-original.svg",
    category: "mobile",
    description: "iOS development with Swift and SwiftUI, MVVM architecture, and state management.",
    duration: "10 weeks",
    level: "intermediate",
    rating: 4.8,
    studentsEnrolled: 7100,
  },
  {
    id: 26,
    title: "GraphQL APIs & Federation at Scale",
    instructor: "Nate Brooks",
    price: 43.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/graphql/graphql-plain.svg",
    category: "backend",
    description: "GraphQL schema design, resolvers, federation, and production-grade API architecture.",
    duration: "7 weeks",
    level: "intermediate",
    rating: 4.6,
    studentsEnrolled: 5300,
  },
  {
    id: 27,
    title: "MongoDB, Redis & Event-Driven Data Layers",
    instructor: "Fatima Al-Rashid",
    price: 45.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mongodb/mongodb-original.svg",
    category: "database",
    description: "NoSQL databases, in-memory caching, event-driven architecture, and real-time data.",
    duration: "8 weeks",
    level: "intermediate",
    rating: 4.7,
    studentsEnrolled: 6700,
  },
  {
    id: 28,
    title: "Edge AI & Embedded ML on Device",
    instructor: "Kevin Zhou",
    price: 59.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/arduino/arduino-original.svg",
    category: "data-science",
    description: "Deploy ML models on edge devices, TensorFlow Lite, ONNX, and IoT optimization.",
    duration: "9 weeks",
    level: "advanced",
    rating: 4.7,
    studentsEnrolled: 3800,
  },
  /* Electrical and electronics */
  {
    id: 29,
    title: "Power Electronics & Smart Grid Fundamentals",
    instructor: "Prof. David Okoro",
    price: 52.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/cplusplus/cplusplus-original.svg",
    category: "backend",
    description: "Power conversion, grid systems, renewable energy integration, and smart grid control.",
    duration: "10 weeks",
    level: "advanced",
    rating: 4.5,
    studentsEnrolled: 2900,
  },
  {
    id: 30,
    title: "Embedded Systems, RTOS & ARM Cortex",
    instructor: "Dr. Ana Morales",
    price: 56.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/c/c-original.svg",
    category: "backend",
    description: "Real-time operating systems, ARM architecture, embedded C, and hardware interfacing.",
    duration: "11 weeks",
    level: "advanced",
    rating: 4.6,
    studentsEnrolled: 3500,
  },
  {
    id: 31,
    title: "MATLAB & Simulink for Electrical Engineers",
    instructor: "Prof. Lars Bergstrom",
    price: 49.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/matlab/matlab-original.svg",
    category: "data-science",
    description: "MATLAB programming, Simulink modeling for control systems and signal processing.",
    duration: "8 weeks",
    level: "intermediate",
    rating: 4.6,
    studentsEnrolled: 4200,
  },
  {
    id: 32,
    title: "VLSI, Verilog & Digital Design Flow",
    instructor: "Dr. Kavitha Iyer",
    price: 63.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/cplusplus/cplusplus-original.svg",
    category: "backend",
    description: "VLSI design, Verilog HDL, synthesis, place & route, and FPGA implementation.",
    duration: "12 weeks",
    level: "advanced",
    rating: 4.7,
    studentsEnrolled: 2800,
  },
  {
    id: 33,
    title: "Renewable Energy, EV Drives & Motor Control",
    instructor: "James O'Brien",
    price: 54.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg",
    category: "data-science",
    description: "Renewable energy systems, electric vehicle drives, power electronics, and control engineering.",
    duration: "10 weeks",
    level: "advanced",
    rating: 4.6,
    studentsEnrolled: 3100,
  },
  /* Mechanical and manufacturing */
  {
    id: 34,
    title: "CAD/CAM, AutoCAD & Parametric Modeling",
    instructor: "Michael Torres",
    price: 47.99,
    img: "https://cdn.jsdelivr.net/npm/simple-icons@11.14.0/icons/autocad.svg",
    category: "backend",
    description: "Computer-aided design, AutoCAD, parametric modeling, and CAM programming basics.",
    duration: "8 weeks",
    level: "intermediate",
    rating: 4.5,
    studentsEnrolled: 3200,
  },
  {
    id: 35,
    title: "Robotics, ROS 2 & Motion Planning",
    instructor: "Dr. Sophie Nakamura",
    price: 58.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg",
    category: "backend",
    description: "Robotics framework ROS 2, kinematics, motion planning algorithms, and robot simulation.",
    duration: "11 weeks",
    level: "advanced",
    rating: 4.7,
    studentsEnrolled: 3900,
  },
  {
    id: 36,
    title: "FEA, MATLAB & Structural Simulation Basics",
    instructor: "Prof. Markus Lindholm",
    price: 51.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/matlab/matlab-original.svg",
    category: "data-science",
    description: "Finite element analysis, MATLAB simulation tools, stress analysis, and material modeling.",
    duration: "9 weeks",
    level: "advanced",
    rating: 4.6,
    studentsEnrolled: 2700,
  },
  {
    id: 37,
    title: "Thermo-Fluids, CFD & Heat Transfer Essentials",
    instructor: "Dr. Rina Kapoor",
    price: 53.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg",
    category: "data-science",
    description: "Computational fluid dynamics, heat transfer simulation, thermodynamics modeling.",
    duration: "10 weeks",
    level: "advanced",
    rating: 4.6,
    studentsEnrolled: 2500,
  },
  {
    id: 38,
    title: "Additive Manufacturing & 3D Printing Workflows",
    instructor: "Carlos Mendes",
    price: 44.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/blender/blender-original.svg",
    category: "backend",
    description: "3D printing technologies, CAD for additive manufacturing, slicing, and process optimization.",
    duration: "6 weeks",
    level: "beginner",
    rating: 4.5,
    studentsEnrolled: 3400,
  },
  /* Civil and infrastructure */
  {
    id: 39,
    title: "Structural Analysis: Steel, Concrete & Codes",
    instructor: "Eng. Sarah Mbeki",
    price: 50.99,
    img: "https://cdn.jsdelivr.net/npm/simple-icons@11.14.0/icons/autocad.svg",
    category: "backend",
    description: "Structural design, steel and concrete analysis, building codes, and safety standards.",
    duration: "10 weeks",
    level: "advanced",
    rating: 4.5,
    studentsEnrolled: 2400,
  },
  {
    id: 40,
    title: "BIM, Civil 3D & Transportation Design",
    instructor: "Daniel Frost",
    price: 52.99,
    img: "https://cdn.jsdelivr.net/npm/simple-icons@11.14.0/icons/autodesk.svg",
    category: "backend",
    description: "Building information modeling, Civil 3D, road/bridge design, and infrastructure planning.",
    duration: "9 weeks",
    level: "advanced",
    rating: 4.6,
    studentsEnrolled: 2600,
  },
  {
    id: 41,
    title: "Geotechnical Engineering & Foundation Design",
    instructor: "Prof. Yuki Tanaka",
    price: 49.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/matlab/matlab-original.svg",
    category: "data-science",
    description: "Soil mechanics, foundation design, geotechnical analysis, and stability assessment.",
    duration: "10 weeks",
    level: "advanced",
    rating: 4.5,
    studentsEnrolled: 2100,
  },
  {
    id: 42,
    title: "Sustainable Construction & Green Building Standards",
    instructor: "Amelia Costa",
    price: 46.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg",
    category: "backend",
    description: "LEED certification, green building standards, sustainable materials, and environmental impact.",
    duration: "7 weeks",
    level: "beginner",
    rating: 4.5,
    studentsEnrolled: 2800,
  },
  /* Chemical and process */
  {
    id: 43,
    title: "Process Design, Mass Balance & Unit Operations",
    instructor: "Dr. Omar Farouk",
    price: 51.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg",
    category: "database",
    description: "Chemical process design, material balance, reactor design, and unit operations fundamentals.",
    duration: "10 weeks",
    level: "advanced",
    rating: 4.6,
    studentsEnrolled: 1900,
  },
  {
    id: 44,
    title: "Process Safety, HAZOP & Risk in Chemical Plants",
    instructor: "Laura Petrov",
    price: 55.99,
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/bash/bash-original.svg",
    category: "backend",
    description: "Process safety management, HAZOP studies, risk assessment, and emergency response planning.",
    duration: "8 weeks",
    level: "advanced",
    rating: 4.6,
    studentsEnrolled: 1700,
  },
];

export default fakeData;

